// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: auth_identities_queries.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countAuthIdentitiesForUser = `-- name: CountAuthIdentitiesForUser :one
SELECT COUNT(*)::bigint AS count
FROM auth_identities
WHERE user_id = $1
`

func (q *Queries) CountAuthIdentitiesForUser(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countAuthIdentitiesForUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteAuthIdentity = `-- name: DeleteAuthIdentity :one
DELETE FROM auth_identities
WHERE id = $1
RETURNING id, user_id, provider, subject, email, email_verified, apple_refresh_token_encrypted, created_at, last_used_at
`

func (q *Queries) DeleteAuthIdentity(ctx context.Context, id uuid.UUID) (AuthIdentity, error) {
	row := q.db.QueryRow(ctx, deleteAuthIdentity, id)
	var i AuthIdentity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.Subject,
		&i.Email,
		&i.EmailVerified,
		&i.AppleRefreshTokenEncrypted,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const getAppleRefreshTokenEncrypted = `-- name: GetAppleRefreshTokenEncrypted :one
SELECT apple_refresh_token_encrypted
FROM auth_identities
WHERE id = $1
`

func (q *Queries) GetAppleRefreshTokenEncrypted(ctx context.Context, id uuid.UUID) ([]byte, error) {
	row := q.db.QueryRow(ctx, getAppleRefreshTokenEncrypted, id)
	var apple_refresh_token_encrypted []byte
	err := row.Scan(&apple_refresh_token_encrypted)
	return apple_refresh_token_encrypted, err
}

const getAuthIdentitiesForUser = `-- name: GetAuthIdentitiesForUser :many
SELECT id, user_id, provider, subject, email, email_verified, apple_refresh_token_encrypted, created_at, last_used_at
FROM auth_identities
WHERE user_id = $1
ORDER BY created_at ASC
`

func (q *Queries) GetAuthIdentitiesForUser(ctx context.Context, userID uuid.UUID) ([]AuthIdentity, error) {
	rows, err := q.db.Query(ctx, getAuthIdentitiesForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuthIdentity
	for rows.Next() {
		var i AuthIdentity
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Provider,
			&i.Subject,
			&i.Email,
			&i.EmailVerified,
			&i.AppleRefreshTokenEncrypted,
			&i.CreatedAt,
			&i.LastUsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAuthIdentity = `-- name: GetAuthIdentity :one
SELECT id, user_id, provider, subject, email, email_verified, apple_refresh_token_encrypted, created_at, last_used_at
FROM auth_identities
WHERE provider = $1 AND subject = $2
`

type GetAuthIdentityParams struct {
	Provider string `json:"provider"`
	Subject  string `json:"subject"`
}

func (q *Queries) GetAuthIdentity(ctx context.Context, arg GetAuthIdentityParams) (AuthIdentity, error) {
	row := q.db.QueryRow(ctx, getAuthIdentity, arg.Provider, arg.Subject)
	var i AuthIdentity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.Subject,
		&i.Email,
		&i.EmailVerified,
		&i.AppleRefreshTokenEncrypted,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const getAuthIdentityByID = `-- name: GetAuthIdentityByID :one
SELECT id, user_id, provider, subject, email, email_verified, apple_refresh_token_encrypted, created_at, last_used_at
FROM auth_identities
WHERE id = $1
`

func (q *Queries) GetAuthIdentityByID(ctx context.Context, id uuid.UUID) (AuthIdentity, error) {
	row := q.db.QueryRow(ctx, getAuthIdentityByID, id)
	var i AuthIdentity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.Subject,
		&i.Email,
		&i.EmailVerified,
		&i.AppleRefreshTokenEncrypted,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const insertAuthIdentity = `-- name: InsertAuthIdentity :one
INSERT INTO auth_identities (
    user_id,
    provider,
    subject,
    email,
    email_verified
) VALUES (
    $1, $2, $3, $4, $5
)
ON CONFLICT (provider, subject) DO UPDATE SET
    last_used_at = NOW()
RETURNING id, user_id, provider, subject, email, email_verified, apple_refresh_token_encrypted, created_at, last_used_at
`

type InsertAuthIdentityParams struct {
	UserID        uuid.UUID   `json:"user_id"`
	Provider      string      `json:"provider"`
	Subject       string      `json:"subject"`
	Email         pgtype.Text `json:"email"`
	EmailVerified pgtype.Bool `json:"email_verified"`
}

// ON CONFLICT guard protects against two concurrent /auth/apple calls for the
// same new identity. The losing caller gets RETURNING from the winner's row.
func (q *Queries) InsertAuthIdentity(ctx context.Context, arg InsertAuthIdentityParams) (AuthIdentity, error) {
	row := q.db.QueryRow(ctx, insertAuthIdentity,
		arg.UserID,
		arg.Provider,
		arg.Subject,
		arg.Email,
		arg.EmailVerified,
	)
	var i AuthIdentity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.Subject,
		&i.Email,
		&i.EmailVerified,
		&i.AppleRefreshTokenEncrypted,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const setAppleRefreshTokenEncrypted = `-- name: SetAppleRefreshTokenEncrypted :exec
UPDATE auth_identities
SET apple_refresh_token_encrypted = $2
WHERE id = $1
`

type SetAppleRefreshTokenEncryptedParams struct {
	ID                         uuid.UUID `json:"id"`
	AppleRefreshTokenEncrypted []byte    `json:"apple_refresh_token_encrypted"`
}

func (q *Queries) SetAppleRefreshTokenEncrypted(ctx context.Context, arg SetAppleRefreshTokenEncryptedParams) error {
	_, err := q.db.Exec(ctx, setAppleRefreshTokenEncrypted, arg.ID, arg.AppleRefreshTokenEncrypted)
	return err
}

const updateAuthIdentityEmail = `-- name: UpdateAuthIdentityEmail :exec
UPDATE auth_identities
SET email = $2,
    email_verified = $3
WHERE id = $1
`

type UpdateAuthIdentityEmailParams struct {
	ID            uuid.UUID   `json:"id"`
	Email         pgtype.Text `json:"email"`
	EmailVerified pgtype.Bool `json:"email_verified"`
}

// Email is informational metadata; refresh it opportunistically when the
// provider hands us a new value on a subsequent sign-in.
func (q *Queries) UpdateAuthIdentityEmail(ctx context.Context, arg UpdateAuthIdentityEmailParams) error {
	_, err := q.db.Exec(ctx, updateAuthIdentityEmail, arg.ID, arg.Email, arg.EmailVerified)
	return err
}

const updateAuthIdentityLastUsed = `-- name: UpdateAuthIdentityLastUsed :exec
UPDATE auth_identities
SET last_used_at = NOW()
WHERE id = $1
`

func (q *Queries) UpdateAuthIdentityLastUsed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, updateAuthIdentityLastUsed, id)
	return err
}
