// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: copyfrom.go

package db

import (
	"context"
)

// iteratorForInsertPushReceipts implements pgx.CopyFromSource.
type iteratorForInsertPushReceipts struct {
	rows                 []InsertPushReceiptsParams
	skippedFirstNextCall bool
}

func (r *iteratorForInsertPushReceipts) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForInsertPushReceipts) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].TicketID,
		r.rows[0].PushToken,
	}, nil
}

func (r iteratorForInsertPushReceipts) Err() error {
	return nil
}

func (q *Queries) InsertPushReceipts(ctx context.Context, arg []InsertPushReceiptsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"push_receipts"}, []string{"ticket_id", "push_token"}, &iteratorForInsertPushReceipts{rows: arg})
}
