// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: invite_queries.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const deleteInvite = `-- name: DeleteInvite :exec
DELETE FROM invites WHERE id = $1
`

func (q *Queries) DeleteInvite(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteInvite, id)
	return err
}

const getGroupPreviewByID = `-- name: GetGroupPreviewByID :one
SELECT
    g.id,
    g.name,
    g.description,
    g.image_url,
    g.blurhash,
    g.start_time,
    g.end_time,
    (SELECT COUNT(*) FROM user_groups ug WHERE ug.group_id = g.id AND ug.deleted_at IS NULL)::int AS member_count
FROM groups g
WHERE g.id = $1 AND g.deleted_at IS NULL
`

type GetGroupPreviewByIDRow struct {
	ID          uuid.UUID        `json:"id"`
	Name        string           `json:"name"`
	Description pgtype.Text      `json:"description"`
	ImageUrl    pgtype.Text      `json:"image_url"`
	Blurhash    pgtype.Text      `json:"blurhash"`
	StartTime   pgtype.Timestamp `json:"start_time"`
	EndTime     pgtype.Timestamp `json:"end_time"`
	MemberCount int32            `json:"member_count"`
}

func (q *Queries) GetGroupPreviewByID(ctx context.Context, id uuid.UUID) (GetGroupPreviewByIDRow, error) {
	row := q.db.QueryRow(ctx, getGroupPreviewByID, id)
	var i GetGroupPreviewByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.ImageUrl,
		&i.Blurhash,
		&i.StartTime,
		&i.EndTime,
		&i.MemberCount,
	)
	return i, err
}

const getInviteByCode = `-- name: GetInviteByCode :one
SELECT id, code, group_id, created_by, expires_at, max_uses, use_count, created_at FROM invites WHERE code = $1
`

func (q *Queries) GetInviteByCode(ctx context.Context, code string) (Invite, error) {
	row := q.db.QueryRow(ctx, getInviteByCode, code)
	var i Invite
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.GroupID,
		&i.CreatedBy,
		&i.ExpiresAt,
		&i.MaxUses,
		&i.UseCount,
		&i.CreatedAt,
	)
	return i, err
}

const getInvitesByGroup = `-- name: GetInvitesByGroup :many
SELECT id, code, group_id, created_by, expires_at, max_uses, use_count, created_at FROM invites WHERE group_id = $1 ORDER BY created_at DESC
`

func (q *Queries) GetInvitesByGroup(ctx context.Context, groupID uuid.UUID) ([]Invite, error) {
	rows, err := q.db.Query(ctx, getInvitesByGroup, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Invite
	for rows.Next() {
		var i Invite
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.GroupID,
			&i.CreatedBy,
			&i.ExpiresAt,
			&i.MaxUses,
			&i.UseCount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const incrementInviteUseCount = `-- name: IncrementInviteUseCount :exec
UPDATE invites SET use_count = use_count + 1 WHERE id = $1
`

func (q *Queries) IncrementInviteUseCount(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, incrementInviteUseCount, id)
	return err
}

const insertInvite = `-- name: InsertInvite :one
INSERT INTO invites (code, group_id, created_by, expires_at, max_uses)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, code, group_id, created_by, expires_at, max_uses, use_count, created_at
`

type InsertInviteParams struct {
	Code      string             `json:"code"`
	GroupID   uuid.UUID          `json:"group_id"`
	CreatedBy uuid.UUID          `json:"created_by"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	MaxUses   int32              `json:"max_uses"`
}

func (q *Queries) InsertInvite(ctx context.Context, arg InsertInviteParams) (Invite, error) {
	row := q.db.QueryRow(ctx, insertInvite,
		arg.Code,
		arg.GroupID,
		arg.CreatedBy,
		arg.ExpiresAt,
		arg.MaxUses,
	)
	var i Invite
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.GroupID,
		&i.CreatedBy,
		&i.ExpiresAt,
		&i.MaxUses,
		&i.UseCount,
		&i.CreatedAt,
	)
	return i, err
}
