// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: push_token_queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteOldReceipts = `-- name: DeleteOldReceipts :exec
DELETE FROM push_receipts WHERE created_at < now() - interval '24 hours'
`

func (q *Queries) DeleteOldReceipts(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteOldReceipts)
	return err
}

const deletePushTokenByValue = `-- name: DeletePushTokenByValue :exec
UPDATE device_keys SET expo_push_token = NULL
WHERE expo_push_token = $1
`

func (q *Queries) DeletePushTokenByValue(ctx context.Context, expoPushToken pgtype.Text) error {
	_, err := q.db.Exec(ctx, deletePushTokenByValue, expoPushToken)
	return err
}

const deleteReceipts = `-- name: DeleteReceipts :exec
DELETE FROM push_receipts WHERE ticket_id = ANY($1::text[])
`

func (q *Queries) DeleteReceipts(ctx context.Context, dollar_1 []string) error {
	_, err := q.db.Exec(ctx, deleteReceipts, dollar_1)
	return err
}

const getPendingReceipts = `-- name: GetPendingReceipts :many
SELECT ticket_id, push_token FROM push_receipts
WHERE created_at < now() - interval '15 minutes'
LIMIT 1000
`

type GetPendingReceiptsRow struct {
	TicketID  string `json:"ticket_id"`
	PushToken string `json:"push_token"`
}

func (q *Queries) GetPendingReceipts(ctx context.Context) ([]GetPendingReceiptsRow, error) {
	rows, err := q.db.Query(ctx, getPendingReceipts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPendingReceiptsRow
	for rows.Next() {
		var i GetPendingReceiptsRow
		if err := rows.Scan(&i.TicketID, &i.PushToken); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertPushReceipt = `-- name: InsertPushReceipt :exec
INSERT INTO push_receipts (ticket_id, push_token) VALUES ($1, $2)
`

type InsertPushReceiptParams struct {
	TicketID  string `json:"ticket_id"`
	PushToken string `json:"push_token"`
}

func (q *Queries) InsertPushReceipt(ctx context.Context, arg InsertPushReceiptParams) error {
	_, err := q.db.Exec(ctx, insertPushReceipt, arg.TicketID, arg.PushToken)
	return err
}

type InsertPushReceiptsParams struct {
	TicketID  string `json:"ticket_id"`
	PushToken string `json:"push_token"`
}
