// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: refresh_tokens_queries.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const deleteStaleRefreshTokens = `-- name: DeleteStaleRefreshTokens :exec
DELETE FROM refresh_tokens
WHERE expires_at < NOW() - INTERVAL '30 days'
   OR revoked_at < NOW() - INTERVAL '30 days'
`

// 30-day retention window after expiry/revocation for forensic tail on theft
// incidents. Tune later.
func (q *Queries) DeleteStaleRefreshTokens(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteStaleRefreshTokens)
	return err
}

const getActiveRefreshTokensForUser = `-- name: GetActiveRefreshTokensForUser :many
SELECT id, user_id, device_identifier, token_hash, expires_at, created_at, last_used_at, revoked_at, replaced_by, user_agent
FROM refresh_tokens
WHERE user_id = $1
  AND revoked_at IS NULL
  AND expires_at > NOW()
ORDER BY created_at DESC
`

func (q *Queries) GetActiveRefreshTokensForUser(ctx context.Context, userID uuid.UUID) ([]RefreshToken, error) {
	rows, err := q.db.Query(ctx, getActiveRefreshTokensForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RefreshToken
	for rows.Next() {
		var i RefreshToken
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.DeviceIdentifier,
			&i.TokenHash,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.LastUsedAt,
			&i.RevokedAt,
			&i.ReplacedBy,
			&i.UserAgent,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRefreshTokenByHash = `-- name: GetRefreshTokenByHash :one
SELECT id, user_id, device_identifier, token_hash, expires_at, created_at, last_used_at, revoked_at, replaced_by, user_agent
FROM refresh_tokens
WHERE token_hash = $1
`

func (q *Queries) GetRefreshTokenByHash(ctx context.Context, tokenHash []byte) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, getRefreshTokenByHash, tokenHash)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DeviceIdentifier,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.RevokedAt,
		&i.ReplacedBy,
		&i.UserAgent,
	)
	return i, err
}

const getRefreshTokenByID = `-- name: GetRefreshTokenByID :one
SELECT id, user_id, device_identifier, token_hash, expires_at, created_at, last_used_at, revoked_at, replaced_by, user_agent
FROM refresh_tokens
WHERE id = $1
`

func (q *Queries) GetRefreshTokenByID(ctx context.Context, id uuid.UUID) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, getRefreshTokenByID, id)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DeviceIdentifier,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.RevokedAt,
		&i.ReplacedBy,
		&i.UserAgent,
	)
	return i, err
}

const insertRefreshToken = `-- name: InsertRefreshToken :one
INSERT INTO refresh_tokens (
    user_id,
    device_identifier,
    token_hash,
    expires_at,
    user_agent
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id, user_id, device_identifier, token_hash, expires_at, created_at, last_used_at, revoked_at, replaced_by, user_agent
`

type InsertRefreshTokenParams struct {
	UserID           uuid.UUID        `json:"user_id"`
	DeviceIdentifier string           `json:"device_identifier"`
	TokenHash        []byte           `json:"token_hash"`
	ExpiresAt        pgtype.Timestamp `json:"expires_at"`
	UserAgent        pgtype.Text      `json:"user_agent"`
}

func (q *Queries) InsertRefreshToken(ctx context.Context, arg InsertRefreshTokenParams) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, insertRefreshToken,
		arg.UserID,
		arg.DeviceIdentifier,
		arg.TokenHash,
		arg.ExpiresAt,
		arg.UserAgent,
	)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DeviceIdentifier,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.RevokedAt,
		&i.ReplacedBy,
		&i.UserAgent,
	)
	return i, err
}

const revokeAllRefreshTokensForUser = `-- name: RevokeAllRefreshTokensForUser :exec
UPDATE refresh_tokens
SET revoked_at = NOW()
WHERE user_id = $1
  AND revoked_at IS NULL
`

func (q *Queries) RevokeAllRefreshTokensForUser(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeAllRefreshTokensForUser, userID)
	return err
}

const revokeOtherRefreshTokensForUser = `-- name: RevokeOtherRefreshTokensForUser :many
UPDATE refresh_tokens
SET revoked_at = NOW()
WHERE user_id = $1
  AND device_identifier != $2
  AND revoked_at IS NULL
RETURNING device_identifier
`

type RevokeOtherRefreshTokensForUserParams struct {
	UserID           uuid.UUID `json:"user_id"`
	DeviceIdentifier string    `json:"device_identifier"`
}

// Revokes every active refresh token for this user except those on the
// specified device_identifier. Returns the device_identifiers that were
// revoked so the caller can NULL out push tokens for those devices.
func (q *Queries) RevokeOtherRefreshTokensForUser(ctx context.Context, arg RevokeOtherRefreshTokensForUserParams) ([]string, error) {
	rows, err := q.db.Query(ctx, revokeOtherRefreshTokensForUser, arg.UserID, arg.DeviceIdentifier)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var device_identifier string
		if err := rows.Scan(&device_identifier); err != nil {
			return nil, err
		}
		items = append(items, device_identifier)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeRefreshToken = `-- name: RevokeRefreshToken :exec
UPDATE refresh_tokens
SET revoked_at = NOW()
WHERE id = $1
  AND revoked_at IS NULL
`

func (q *Queries) RevokeRefreshToken(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeRefreshToken, id)
	return err
}

const revokeRefreshTokenFamily = `-- name: RevokeRefreshTokenFamily :exec
WITH RECURSIVE forward AS (
    SELECT rt.id AS token_id, rt.replaced_by
    FROM refresh_tokens rt
    WHERE rt.id = $1

    UNION

    SELECT rt.id, rt.replaced_by
    FROM refresh_tokens rt
    JOIN forward f ON rt.id = f.replaced_by
),
backward AS (
    SELECT rt.id AS token_id, rt.replaced_by
    FROM refresh_tokens rt
    WHERE rt.id = $1

    UNION

    SELECT rt.id, rt.replaced_by
    FROM refresh_tokens rt
    JOIN backward b ON rt.replaced_by = b.token_id
)
UPDATE refresh_tokens
SET revoked_at = COALESCE(revoked_at, NOW())
WHERE id IN (SELECT token_id FROM forward)
   OR id IN (SELECT token_id FROM backward)
`

// Theft response: walk the replaced_by chain both directions from the offending
// row and revoke every row in the family. Two separate recursive CTEs — one
// traces forward through replaced_by pointers, the other traces backward to
// rows that pointed at anything in the family. Postgres forbids a recursive
// CTE referencing itself twice in one UNION, so splitting is necessary.
func (q *Queries) RevokeRefreshTokenFamily(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeRefreshTokenFamily, id)
	return err
}

const rotateRefreshToken = `-- name: RotateRefreshToken :exec
UPDATE refresh_tokens
SET revoked_at = NOW(),
    replaced_by = $2,
    last_used_at = NOW()
WHERE id = $1
`

type RotateRefreshTokenParams struct {
	ID         uuid.UUID  `json:"id"`
	ReplacedBy *uuid.UUID `json:"replaced_by"`
}

// Marks the old row revoked and links it to the newly-issued replacement.
// Callers must run this inside the same tx that inserts the new row so a
// failure rolls back both.
func (q *Queries) RotateRefreshToken(ctx context.Context, arg RotateRefreshTokenParams) error {
	_, err := q.db.Exec(ctx, rotateRefreshToken, arg.ID, arg.ReplacedBy)
	return err
}
