// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: user_group_queries.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const deleteUserGroup = `-- name: DeleteUserGroup :one
UPDATE user_groups SET deleted_at = NOW()
WHERE user_id = $1 AND group_id = $2 AND deleted_at IS NULL
RETURNING "id", "user_id", "group_id", "admin", "created_at", "updated_at"
`

type DeleteUserGroupParams struct {
	UserID  *uuid.UUID `json:"user_id"`
	GroupID *uuid.UUID `json:"group_id"`
}

type DeleteUserGroupRow struct {
	ID        uuid.UUID        `json:"id"`
	UserID    *uuid.UUID       `json:"user_id"`
	GroupID   *uuid.UUID       `json:"group_id"`
	Admin     bool             `json:"admin"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) DeleteUserGroup(ctx context.Context, arg DeleteUserGroupParams) (DeleteUserGroupRow, error) {
	row := q.db.QueryRow(ctx, deleteUserGroup, arg.UserID, arg.GroupID)
	var i DeleteUserGroupRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.GroupID,
		&i.Admin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAllUserGroups = `-- name: GetAllUserGroups :many
SELECT "id", "user_id", "group_id", "admin", "created_at", "updated_at" FROM user_groups WHERE deleted_at IS NULL
`

type GetAllUserGroupsRow struct {
	ID        uuid.UUID        `json:"id"`
	UserID    *uuid.UUID       `json:"user_id"`
	GroupID   *uuid.UUID       `json:"group_id"`
	Admin     bool             `json:"admin"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) GetAllUserGroups(ctx context.Context) ([]GetAllUserGroupsRow, error) {
	rows, err := q.db.Query(ctx, getAllUserGroups)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllUserGroupsRow
	for rows.Next() {
		var i GetAllUserGroupsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.GroupID,
			&i.Admin,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllUserGroupsForGroup = `-- name: GetAllUserGroupsForGroup :many
SELECT "id", "user_id", "group_id", "admin", "created_at", "updated_at" FROM user_groups WHERE group_id = $1 AND deleted_at IS NULL ORDER BY created_at ASC
`

type GetAllUserGroupsForGroupRow struct {
	ID        uuid.UUID        `json:"id"`
	UserID    *uuid.UUID       `json:"user_id"`
	GroupID   *uuid.UUID       `json:"group_id"`
	Admin     bool             `json:"admin"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) GetAllUserGroupsForGroup(ctx context.Context, groupID *uuid.UUID) ([]GetAllUserGroupsForGroupRow, error) {
	rows, err := q.db.Query(ctx, getAllUserGroupsForGroup, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllUserGroupsForGroupRow
	for rows.Next() {
		var i GetAllUserGroupsForGroupRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.GroupID,
			&i.Admin,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllUserGroupsForUser = `-- name: GetAllUserGroupsForUser :many
SELECT "id", "user_id", "group_id", "admin", "created_at", "updated_at" FROM user_groups WHERE user_id = $1 AND deleted_at IS NULL
`

type GetAllUserGroupsForUserRow struct {
	ID        uuid.UUID        `json:"id"`
	UserID    *uuid.UUID       `json:"user_id"`
	GroupID   *uuid.UUID       `json:"group_id"`
	Admin     bool             `json:"admin"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) GetAllUserGroupsForUser(ctx context.Context, userID *uuid.UUID) ([]GetAllUserGroupsForUserRow, error) {
	rows, err := q.db.Query(ctx, getAllUserGroupsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllUserGroupsForUserRow
	for rows.Next() {
		var i GetAllUserGroupsForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.GroupID,
			&i.Admin,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserGroupByGroupIDAndUserID = `-- name: GetUserGroupByGroupIDAndUserID :one
SELECT "id", "user_id", "group_id", "admin", "created_at", "updated_at" FROM user_groups WHERE user_id = $1 AND group_id = $2 AND deleted_at IS NULL
`

type GetUserGroupByGroupIDAndUserIDParams struct {
	UserID  *uuid.UUID `json:"user_id"`
	GroupID *uuid.UUID `json:"group_id"`
}

type GetUserGroupByGroupIDAndUserIDRow struct {
	ID        uuid.UUID        `json:"id"`
	UserID    *uuid.UUID       `json:"user_id"`
	GroupID   *uuid.UUID       `json:"group_id"`
	Admin     bool             `json:"admin"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) GetUserGroupByGroupIDAndUserID(ctx context.Context, arg GetUserGroupByGroupIDAndUserIDParams) (GetUserGroupByGroupIDAndUserIDRow, error) {
	row := q.db.QueryRow(ctx, getUserGroupByGroupIDAndUserID, arg.UserID, arg.GroupID)
	var i GetUserGroupByGroupIDAndUserIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.GroupID,
		&i.Admin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserGroupByID = `-- name: GetUserGroupByID :one
SELECT "id", "user_id", "group_id", "admin", "created_at", "updated_at" FROM user_groups WHERE id = $1 AND deleted_at IS NULL
`

type GetUserGroupByIDRow struct {
	ID        uuid.UUID        `json:"id"`
	UserID    *uuid.UUID       `json:"user_id"`
	GroupID   *uuid.UUID       `json:"group_id"`
	Admin     bool             `json:"admin"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) GetUserGroupByID(ctx context.Context, id uuid.UUID) (GetUserGroupByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserGroupByID, id)
	var i GetUserGroupByIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.GroupID,
		&i.Admin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertUserGroup = `-- name: InsertUserGroup :one
INSERT INTO user_groups
    ("user_id", "group_id", "admin")
VALUES ($1, $2, $3)
ON CONFLICT (user_id, group_id) WHERE deleted_at IS NULL DO NOTHING
RETURNING id, user_id, group_id, created_at, updated_at, admin, deleted_at
`

type InsertUserGroupParams struct {
	UserID  *uuid.UUID `json:"user_id"`
	GroupID *uuid.UUID `json:"group_id"`
	Admin   bool       `json:"admin"`
}

func (q *Queries) InsertUserGroup(ctx context.Context, arg InsertUserGroupParams) (UserGroup, error) {
	row := q.db.QueryRow(ctx, insertUserGroup, arg.UserID, arg.GroupID, arg.Admin)
	var i UserGroup
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.GroupID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Admin,
		&i.DeletedAt,
	)
	return i, err
}

const updateUserGroup = `-- name: UpdateUserGroup :one
UPDATE user_groups
SET
    "admin" = $3
WHERE user_id = $1 AND group_id = $2 AND deleted_at IS NULL
RETURNING "id", "user_id", "group_id", "admin", "created_at", "updated_at"
`

type UpdateUserGroupParams struct {
	UserID  *uuid.UUID `json:"user_id"`
	GroupID *uuid.UUID `json:"group_id"`
	Admin   bool       `json:"admin"`
}

type UpdateUserGroupRow struct {
	ID        uuid.UUID        `json:"id"`
	UserID    *uuid.UUID       `json:"user_id"`
	GroupID   *uuid.UUID       `json:"group_id"`
	Admin     bool             `json:"admin"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) UpdateUserGroup(ctx context.Context, arg UpdateUserGroupParams) (UpdateUserGroupRow, error) {
	row := q.db.QueryRow(ctx, updateUserGroup, arg.UserID, arg.GroupID, arg.Admin)
	var i UpdateUserGroupRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.GroupID,
		&i.Admin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
